name: Deploy to GitHub Pages (Legacy - Most Reliable)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual deployment

# Add permissions for the workflow
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment runs at a time
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate project structure
      run: |
        echo "🔍 Validating project structure..."
        
        # Check essential files
        required_files=("index.html" "main.js" "style.css")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file found"
          else
            echo "❌ $file missing"
            exit 1
          fi
        done
        
        # Check engine directory
        if [ -d "engine" ]; then
          echo "✅ engine/ directory found"
          engine_files=$(ls engine/*.js 2>/dev/null | wc -l)
          echo "📁 Found $engine_files engine files"
        else
          echo "❌ engine/ directory missing"
          exit 1
        fi
        
        # Check game directory
        if [ -d "game" ]; then
          echo "✅ game/ directory found"
          game_files=$(ls game/*.js 2>/dev/null | wc -l)
          echo "🎮 Found $game_files game files"
        else
          echo "❌ game/ directory missing"
          exit 1
        fi
        
        echo "✅ Project structure validation passed!"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        force_orphan: true
        
    - name: Verify deployment
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "📱 Your site should be available at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
        echo "⏱️  It may take a few minutes for changes to appear"
